name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.20.0
      - run: npm install && npm install -g @lhci/cli@0.12.x
      - run: npm run build
      - run: npm run lhci:build
      - run: |
          echo $LHCI_GITHUB_APP_TOKEN
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}